title: <p align="center"> Yosafat </p>

logo: "/images/profile.png?raw=true" 

description: 
  <p align="center">
  <a href="https://yoss7054.notion.site/">Resume</a> |
  <a href="https://www.linkedin.com/in/yosafat-7054/">LinkedIn</a> |
  <a href="https://github.com/crypter70">GitHub</a>
  </p>
  
  <p align="justify">
  Experienced Data Analyst with 1 year of expertise in data analysis, data visualization, data wrangling, statistical analysis, machine learning, and web scraping. Skilled in extracting and interpreting actionable insights to drive data-informed decision making. Seeking opportunities in data-driven roles such as Data Analyst or Data Scientist. Experienced in the organization for 2 years, actively leading and collaborating in teams.
  </p>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
