title: <p align="center"> Yosafat </p>

logo: "/images/profile.png?raw=true" 

description: 
  <p align="center">
  <a href="pdf/ATS CV. Yosafat (Gab).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yosafat-7054/">LinkedIn</a> |
  <a href="https://github.com/crypter70">GitHub</a>
  </p>
  
  <p align="justify">
  I am a computer science student with major skills in web scraping, data analysis, and data visualization. Currently, I am working as a Data Analyst at the Data Center of Universitas Pendidikan Indonesia. Active in organizations such as Curriculum Core Team at Google Developer Student Club (GDSC) Universitas Pendidikan Indonesia. Experienced in the organization for 2 years and actively lead and collaborate in teams.
  </p>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
